watch_stylesheet: true
watch_config: true
debug: false

komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"

bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 36
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: ["komorebi_workspaces", "taskbar"]
      center: ["launchpad", "clock", "media"]
      right:
        [
          "systray",
          "cpu",
          "memory",
          "disk",
          "traffic",
          "volume",
          "notes",
          "power_menu",
        ]

widgets:
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: "󰐽"
      label_workspace_active_btn: "󰐾"
      label_workspace_populated_btn: "󰐾"
      label_default_name: ""
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      animation: true
      app_icons:
        enabled_populated: false
        enabled_active: false
        size: 12
        max_icons: 0
        hide_label: false
        hide_duplicates: false
        hide_floating: false
      btn_shadow:
        enabled: false

  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      tooltip: false
      show_only_visible: false
      strict_filtering: false
      monitor_exclusive: false
      animation:
        enabled: true
      preview:
        enabled: true
        width: 450
        delay: 400
        padding: 12
      ignore_apps:
        processes: []
        titles: []
        classes: []

  launchpad:
    type: "yasb.launchpad.LaunchpadWidget"
    options:
      label: "<span>󰣆</span>"
      search_placeholder: "Search apps..."
      app_icon_size: 48
      window:
        fullscreen: false
        width: 800
        height: 600
        overlay_block: true
      window_style:
        enable_blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
      window_animation:
        fade_in_duration: 200
        fade_out_duration: 200
      callbacks:
        on_left: "toggle_launchpad"
      app_title_shadow:
        enabled: true
        color: "#00000090"
        offset: [1, 1]
        radius: 2
      app_icon_shadow:
        enabled: true
        color: "#00000090"
        offset: [0, 2]
        radius: 8

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a %d %b  %H:%M}"
      label_alt: "{%A, %d %B %Y  %H:%M}"
      timezones: []
      update_interval: 1000
      callbacks:
        on_left: "toggle_calendar"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      calendar:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        show_holidays: true
        show_week_numbers: true
        holiday_color: "#FF6464"

  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title} - {artist}"
      label_alt: "{title}"
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      max_field_size:
        label: 30
        label_alt: 30
      show_thumbnail: false
      controls_only: false
      controls_left: true
      controls_hide: false
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 16
      icons:
        prev_track: ""
        next_track: ""
        play: ""
        pause: ""
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 90
        max_artist_size: 40
        show_source: true
        show_volume_slider: true
      media_menu_icons:
        play: ""
        pause: ""
        prev_track: ""
        next_track: ""

  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "◀"
      label_expanded: "▶"
      label_position: "right"
      icon_size: 16
      pin_click_modifier: "alt"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: true

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: " {info[percent][total]}%"
      label_alt: " {info[freq][current]} MHz"
      update_interval: 2000
      cpu_thresholds:
        low: 25
        medium: 50
        high: 90
      callbacks:
        on_left: "do_nothing"
        on_middle: "toggle_label"
        on_right: "exec cmd /c Taskmgr"

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: " {virtual_mem_used}"
      label_alt: " {virtual_mem_percent}%"
      update_interval: 5000
      callbacks:
        on_left: "do_nothing"
        on_middle: "toggle_label"
        on_right: "exec cmd /c Taskmgr"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90

  disk:
    type: "yasb.disk.DiskWidget"
    options:
      label: "C: {space[used][percent]}"
      label_alt: "C: {space[used][gb]} / {space[total][gb]}"
      volume_label: "C"
      decimal_display: 1
      update_interval: 60
      group_label:
        volume_labels: ["C", "D", "E", "F"]
        show_label_name: true
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_group"
        on_middle: "toggle_label"
      disk_thresholds:
        low: 25
        medium: 50
        high: 90

  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span>󱙖</span>"
      label_alt: "<span>󱙖</span>  {download_speed} |  {upload_speed}"
      update_interval: 1000
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:network-status"

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "{icon} {level}"
      tooltip: false
      volume_icons:
        - "" # muted
        - "" # 0-10%
        - "" # 11-30%
        - "" # 31-60%
        - "" # 61-100%
      callbacks:
        on_middle: "toggle_mute"
        on_right: "exec cmd.exe /c start ms-settings:sound"
        on_left: "toggle_volume_menu"
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"

  notes:
    type: "yasb.notes.NotesWidget"
    options:
      label: "<span>󰤌</span>"
      label_alt: "{count} notes"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        max_title_size: 150
        show_date_time: true
      icons:
        note: "󰤌"
        delete: ""
        copy: ""
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: ""
      uptime: true
      blur: false
      blur_background: true
      animation_duration: 300
      button_row: 3
      buttons:
        lock: ["", "Lock"]
        signout: ["󰍃", "Sign out"]
        shutdown: ["", "Shut Down"]
        restart: ["", "Restart"]
        hibernate: ["", "Hibernate"]
        cancel: ["󰅖", "Cancel"]
